import tkinter as tk
from tkinter import messagebox,ttk
root=tk.Tk()
root.title("Student Registration Form")
root.geometry("300x400")
name_label=tk.Label(root,text="Enter name")
name_label.pack()
name_textbox=tk.Entry(root)
name_textbox.pack()
choices=['Male','Female']
gender_label=tk.Label(root,text="select gender")
gender_label.pack()
gender_dropdown=ttk.Combobox(root,values=choices)
gender_dropdown.pack()
age_label=tk.Label(root,text="Enter age")
age_label.pack()
age_textbox=tk.Entry(root)
age_textbox.pack()
dOB_label=tk.Label(root,text="Enter date of birth")
dOB_label.pack()
dOB_textbox=tk.Entry(root)
dOB_textbox.pack()
Address_label=tk.Label(root,text="Enter address")
Address_label.pack()
Address_textbox=tk.Entry(root)
Address_textbox.pack()
def submit_data():
    name=name_textbox.get()
    gender=gender_dropdown.get()
    age=age_textbox.get()
    dob=dOB_textbox.get()
    Address=Address_textbox.get()
    messagebox.showinfo("Success","Data submitted")
submit_button=tk.Button(root,text="submit", command=submit_data)
submit_button.pack()
root.mainloop()
