import tkinter as tk
root=tk.Tk()
root.title("Student Registration Form")
name_label=tk.Label(root,text="Enter name:")
name_label.pack()
name_textbox=tk.Entry(root)
name_textbox.pack()
DOB=tk.Label(root,text="Enter date of birth MM/DD/YY ")
DOB.pack()
DOB_textbox=tk.Entry(root)
DOB_textbox.pack()
Gender=tk.Label(root,text="Enter gender")
Gender.pack()
Gender_textbox=tk.Entry(root)
Gender_textbox.pack()
Emailaddress=tk.Label(root,text="Enter email")
Emailaddress.pack()
Email=tk.Entry(root)
Email.pack()
Address=tk.Label(root,text="Residential address")
Address.pack()
Address_textbox=tk.Entry(root)
Address_textbox.pack()
submit_button=tk.Button(root,text="submit")
submit_button.pack()
root.mainloop()
