import pandas as pd
var=pd.DataFrame({"Products":["Laptop","Mouse","Keyboard"], "Price":[50000,5000,3000], "sold":[10,20,5]})
print(var)
print("_"*20)
var.to_csv("Text_new.csv",index=False)
a=pd.read_csv("Text_new.csv")
print(a.to_string(index=False))
print("_"*20)
print(pd.read_csv("Text_new.csv",nrows=1))
print("_"*20)
print(pd.read_csv("Text_new.csv",usecols=[0,2]))
print("_"*20)
print(pd.read_csv("Text_new.csv",skiprows=[1]))
print("_"*20)
print(pd.read_csv("Text_new.csv",index_col="sold"))
print("_"*20)
print(pd.read_csv("Text_new.csv",names=["Items","amount","quantity"]))
print("_"*20)
print(pd.read_csv("Text_new.csv",dtype={"sold":"float"}))